# Generated by Django 5.1.1 on 2024-11-16 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('follow', models.ManyToManyField(related_name='followee', to=settings.AUTH_USER_MODEL)),
                ('place', models.ManyToManyField(blank=True, null=True, related_name='trip', to='trip.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
