# Generated by Django 5.1.1 on 2024-11-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True, default="default.png", upload_to="profile_images/"
            ),
        ),
    ]
