# Generated by Django 5.1.1 on 2024-11-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField(unique=True)),
                ('food_name', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
