# Generated by Django 5.1.3 on 2024-11-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, unique=True)),
                ('addr1', models.CharField(max_length=255)),
                ('addr2', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('img', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
