# Generated by Django 5.1.1 on 2024-11-22 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_remove_trip_users_remove_trip_weather_info_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='weather_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
