# Generated by Django 5.1.1 on 2024-09-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='전화번호'),
        ),
    ]
