# Generated by Django 5.1.1 on 2024-10-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='생일'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(default='', max_length=256, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='전화번호'),
        ),
    ]
